// data_reports.js – Schlagzeilen-Corpus für Spieltags-Berichte (v2, Fable-Ausbau)
// ============================================================================
// Slots:
//   {heim} {gast}          – Teamnamen (immer verfügbar)
//   {sieger} {verlierer}   – nur bei Sieg-Kategorien verfügbar
//   {score}                – bei Sieg-Kategorien AUS SIEGERSICHT ("5:0"),
//                            bei Remis aus Heimsicht ("2:2")
// Regeln für den Laufzeit-Klassifikator (app/reports.js):
//   - Kategorien mit Sieger: kantersieg, deutlich, knapp, ueberraschung
//   - Kategorien ohne Sieger-Garantie: spitzenspiel, kellerduell
//     → dort bei Remis nur Zeilen OHNE {sieger}/{verlierer} ziehen
//   - Priorität bei Mehrfach-Treffern: ueberraschung > spitzenspiel/kellerduell
//     > kantersieg > deutlich > knapp > remis_*
//   - Zeilenwahl matchId-geseedet → Reload zeigt dieselbe Schlagzeile
// Spec: fable-deliverables/paket1-schlagzeilen/SPEC.md (+ FABLE-GRUNDREGELN.md)
// ============================================================================
window.REPORTS = {

    // ---- Tordifferenz >= 4 --------------------------------------------------
    kantersieg: [
        "Schützenfest! {sieger} fegt {verlierer} mit {score} vom Platz",
        "{sieger} kennt kein Erbarmen – {verlierer} geht beim {score} unter",
        "Debakel für {verlierer}: {score}-Klatsche gegen {sieger}",
        "Torfestival: {sieger} spielt sich gegen {verlierer} in einen Rausch",
        "Machtdemonstration – {sieger} lässt {verlierer} beim {score} keine Chance",
        "Ein Nachmittag zum Vergessen: {verlierer} kassiert die {score}-Packung",
        "{sieger} in Gala-Laune, {verlierer} nur Sparringspartner",
        "Kein Spiel, ein Durchmarsch: {sieger} siegt {score}",
        "Bittere Lehrstunde: {verlierer} von {sieger} zerlegt",
        "Die Abwehr? Unauffindbar. {verlierer} verliert {score}",
        "{sieger} schießt {verlierer} ab – die Fans feiern jede Bude",
        "Historisch bitter: {verlierer} erlebt gegen {sieger} ein Fiasko",
        "Wehrlos, mutlos, chancenlos – {verlierer} unterliegt {score}",
        "{sieger} spielt Katz und Maus mit {verlierer}",
        "Kantersieg! {sieger} macht mit {verlierer} kurzen Prozess",
        "Nach dem {score} herrscht bei {verlierer} Katerstimmung",
        "{sieger} trifft nach Belieben – {verlierer} ohne Gegenwehr",
        "Standing Ovations: {sieger} begeistert beim {score} gegen {verlierer}",
        "Für {verlierer} kann es nur besser werden – {score}!",
        "{sieger} im Torrausch, {verlierer} im freien Fall",
        "Ohren angelegt und durchmarschiert: {sieger} siegt {score}",
        "{verlierer} bekommt die Grenzen aufgezeigt – deutlich, deutlicher, {score}",
        "Was für ein Auftritt! {sieger} spielt {verlierer} schwindlig",
        "Böse Klatsche: {verlierer} geht mit wehenden Fahnen unter – {score}",
        "{sieger} feiert ein Fest, {verlierer} erlebt ein Fiasko – {score}",
        "Gnadenlos effizient: {sieger} bestraft jeden Fehler von {verlierer}",
        "Ein Klassenunterschied, in Zahlen gegossen: {score} für {sieger}",
        "{sieger} lässt Taten sprechen – {verlierer} hat dem nichts entgegenzusetzen",
        "Demontage in aller Öffentlichkeit: {verlierer} kassiert ein {score}",
        "Da half kein Flehen: {sieger} kennt beim {score} keine Gnade",
        "Tore wie am Fließband: {sieger} überrennt {verlierer}",
        "{verlierer} wollte kämpfen – {sieger} wollte Tore. {score}.",
        "Einbahnstraßen-Fußball: {sieger} rollt an, {verlierer} schaut zu",
        "Der Torhunger von {sieger} kennt keine Sättigung – {score}",
        "Bittere Pille für {verlierer}: gegen {sieger} setzt es ein {score}",
        "{sieger} zelebriert Fußball, {verlierer} erleidet ihn – {score}",
        "Kein Halten mehr: {sieger} trifft und trifft und trifft – {verlierer} nicht",
        "Wer stoppt {sieger}? {verlierer} jedenfalls nicht – {score}",
        "Lehrbuch-Demontage: {sieger} nimmt {verlierer} auseinander",
        "{verlierer} verlässt den Platz mit hängenden Köpfen – {score}-Debakel",
        "Angriff auf Angriff: {sieger} gönnt {verlierer} keine Verschnaufpause – {score}",
        "Träume zerplatzen: {verlierer} beim {score} ohne jede Chance",
        "Ein Sturmlauf, ein Torregen, ein Statement: {sieger} deklassiert {verlierer}",
        "Für die Statistik: {score}. Für {verlierer}: ein schwarzer Tag.",
        "{sieger} lässt Zahlen sprechen: {score} gegen {verlierer}",
        "Torfestival mit nur einem Gastgeber: {sieger} lädt ein, {verlierer} zahlt",
        "Rückspiel? Darauf freut sich bei {verlierer} nach diesem {score} niemand",
        "Spott von den Rängen, Jubel auf der anderen Seite: {score} für {sieger}",
        "{verlierer} sucht Antworten, {sieger} feiert Tore",
        "Wenn alles läuft: {sieger} erwischt ein Traumspiel – {verlierer} den Albtraum",
        "Deckung? Ordnung? Gegenwehr? Bei {verlierer} an diesem Tag Fremdwörter – {score}",
        "Das nennt man ein Ausrufezeichen: {sieger} siegt {score} gegen {verlierer}"
    ],

    // ---- Tordifferenz 2–3 ---------------------------------------------------
    deutlich: [
        "{sieger} setzt sich souverän mit {score} gegen {verlierer} durch",
        "Verdienter Sieg: {sieger} lässt {verlierer} beim {score} wenig Luft",
        "{sieger} kontrolliert die Partie – {score} gegen {verlierer}",
        "Keine Zweifel: {sieger} schlägt {verlierer} klar mit {score}",
        "{verlierer} müht sich, doch {sieger} ist eine Nummer zu groß",
        "Abgezockt: {sieger} nutzt seine Chancen, {verlierer} nicht",
        "{sieger} liefert – {score} und drei verdiente Punkte",
        "Klare Verhältnisse zwischen {heim} und {gast}: {score}",
        "{sieger} bleibt cool und fährt einen ungefährdeten {score}-Sieg ein",
        "{verlierer} findet kein Mittel gegen {sieger}",
        "Souverän statt spektakulär: {sieger} gewinnt {score}",
        "{sieger} macht früh alles klar – {verlierer} läuft nur hinterher",
        "Standesgemäß: {sieger} besiegt {verlierer} mit {score}",
        "{sieger} dreht nach der Pause auf und siegt {score}",
        "Konzentrierte Vorstellung: {sieger} gibt sich gegen {verlierer} keine Blöße",
        "{verlierer} wehrt sich lange – am Ende steht trotzdem das {score}",
        "Effizienz schlägt Einsatz: {sieger} gewinnt mit {score}",
        "{sieger} untermauert seine Ambitionen mit einem {score} gegen {verlierer}",
        "Nie gefährdet: {sieger} spielt den Sieg über {verlierer} routiniert herunter",
        "{score} – {sieger} erledigt die Pflichtaufgabe gegen {verlierer}",
        "Am Ende steht ein verdientes {score} für {sieger}",
        "{sieger} lässt beim {score} gegen {verlierer} nichts anbrennen",
        "Reife Leistung: {sieger} bezwingt {verlierer} ohne große Aufregung",
        "Zwei Klassen? Nein. Aber ein klarer Unterschied: {score} für {sieger}",
        "{verlierer} bemüht, {sieger} besser – {score}",
        "Arbeitssieg mit Glanzmomenten: {sieger} schlägt {verlierer} {score}",
        "{sieger} spielt seine Möglichkeiten aus – {verlierer} bleibt nur der Frust",
        "Die Punkte gehen verdient an {sieger} – {score} gegen {verlierer}",
        "Souveräner Auftritt: {sieger} hält {verlierer} auf Distanz",
        "{verlierer} findet nie den Hebel – {sieger} gewinnt {score}",
        "Klare Angelegenheit: {sieger} lässt gegen {verlierer} keine Zweifel aufkommen",
        "Ohne Glanz, aber mit Substanz: {score} für {sieger}",
        "{sieger} bleibt seiner Linie treu und schlägt {verlierer} mit {score}",
        "Zu abgeklärt, zu robust, zu gut: {sieger} besiegt {verlierer}",
        "Der Favorit in diesem Duell? Nach dem {score} eindeutig {sieger}",
        "{verlierer} hält eine Weile mit – dann setzt sich Qualität durch: {score}",
        "Keine Kunst, aber Handwerk: {sieger} gewinnt {score}",
        "{sieger} nimmt die Aufgabe ernst und {verlierer} die Punkte ab",
        "Deutliche Verhältnisse: beim {score} gibt es wenig zu deuteln",
        "Sachlich, nüchtern, erfolgreich: {sieger} siegt gegen {verlierer}",
        "{sieger} drückt dem Spiel den Stempel auf – {score}",
        "Ein Sieg der Kategorie 'ungefährdet': {score} für {sieger}",
        "{verlierer} geht leer aus – {sieger} siegt verdient {score}",
        "Stabil, wenn es zählt: {sieger} liefert – {score}",
        "Gegen {sieger} ist an diesem Tag kein Kraut gewachsen – {verlierer} verliert {score}",
        "Chancenverwertung als Matchwinner: {sieger} schlägt {verlierer} {score}",
        "{sieger} trifft zur richtigen Zeit – {verlierer} nicht oft genug",
        "Die Grundtugenden stimmen: {sieger} bezwingt {verlierer} klar",
        "Ergebnis-Fußball in Reinform: {score} für {sieger}",
        "{verlierer} ärgert sich über vergebene Chancen – {sieger} über gar nichts",
        "Die Anzeigetafel spricht eine deutliche Sprache: {score} für {sieger}",
        "Klarer Kurs, klarer Sieg: {sieger} lässt {verlierer} hinter sich"
    ],

    // ---- Tordifferenz 1 -----------------------------------------------------
    knapp: [
        "Zittersieg! {sieger} rettet das {score} gegen {verlierer} über die Zeit",
        "{sieger} gewinnt den Krimi gegen {verlierer} mit {score}",
        "Ein Tor entscheidet: {sieger} schlägt {verlierer} hauchdünn",
        "{verlierer} rennt an, {sieger} hält stand – {score}",
        "Nichts für schwache Nerven: {sieger} siegt knapp mit {score}",
        "Glück oder Können? {sieger} nimmt die Punkte gegen {verlierer} mit",
        "{sieger} erkämpft sich ein hartes {score} gegen {verlierer}",
        "Enges Duell zwischen {heim} und {gast} – am Ende jubelt {sieger} ({score})",
        "{verlierer} verliert unglücklich – das {score} schmerzt",
        "Dreckiger Sieg? Egal! {sieger} nimmt das {score} dankend an",
        "{sieger} entscheidet ein Spiel auf Messers Schneide für sich – {score}",
        "Bis zur letzten Minute offen – dann jubelt {sieger} ({score})",
        "{verlierer} belohnt sich nicht – {sieger} gewinnt {score}",
        "Kampfspiel statt Leckerbissen: {sieger} siegt {score}",
        "{sieger} bleibt im Duell mit {verlierer} das entscheidende Quäntchen kühler",
        "Millimeter-Entscheidung: {score} für {sieger}",
        "{sieger} stiehlt {verlierer} die Show – knapper geht's kaum",
        "Am Ende zählt nur das Ergebnis: {score} für {sieger}",
        "{verlierer} hadert, {sieger} feiert – {score}",
        "Ein Wimpernschlag Unterschied: {sieger} schlägt {verlierer} mit {score}",
        "Nervenschlacht mit Happy End für {sieger} – {score}",
        "Der Fußballgott würfelt – und entscheidet für {sieger}: {score}",
        "{verlierer} war nah dran – {sieger} einen Schritt näher: {score}",
        "Hauchzarte Entscheidung: {sieger} gewinnt das Duell mit {verlierer}",
        "Wer solche Spiele gewinnt, hat Charakter: {sieger} siegt {score}",
        "Drama pur – am Ende jubelt {sieger} ({score})",
        "{score}: mehr Zufall oder mehr Verdienst? {sieger} ist es egal",
        "Die feinen Unterschiede: {sieger} nutzt sie, {verlierer} nicht",
        "Ein Tor trennt Jubel und Frust – {sieger} jubelt, {verlierer} nicht",
        "Beide geben alles, einer bekommt alles: {sieger} gewinnt {score}",
        "Hart erkämpft ist halb gewonnen? Nein, ganz: {score} für {sieger}",
        "{verlierer} fehlt am Ende ein Tor zum Punkt – {sieger} nimmt alles mit",
        "Spiele wie diese entscheiden Kleinigkeiten – heute zugunsten von {sieger} ({score})",
        "Zentimeter, Sekunden, ein Tor: {sieger} gewinnt hauchdünn gegen {verlierer}",
        "Nicht schön, aber selten: drei Punkte für {sieger} beim {score}",
        "Für Feinschmecker war es nichts, für {sieger} alles: {score}",
        "{verlierer} klopft an, {sieger} macht nicht auf – {score}",
        "Ein Duell wie Armdrücken – {sieger} drückt zuletzt: {score}",
        "Krimi ohne Kommissar: Am Tatort jubelt {sieger} – {score}",
        "Das eine Tor, das alles ändert: {sieger} schlägt {verlierer}",
        "Mit Zähnen und Klauen zum {score}: {sieger} will es mehr",
        "Enger geht es kaum – die Punkte sichert sich {sieger}: {score}",
        "Fußball-Roulette: Die Kugel fällt auf {sieger} – {score}",
        "Ein Hauch entscheidet – und er weht in Richtung {sieger} ({score})",
        "Bei {verlierer} regiert der Frust, bei {sieger} die Erleichterung",
        "Das Momentum küsst {sieger} – {score} gegen {verlierer}",
        "Knappe Kiste! {sieger} schnappt sich den Sieg gegen {verlierer}",
        "Wer zuletzt jubelt: {sieger} gewinnt mit {score}",
        "Kleiner Unterschied, große Wirkung: {score} für {sieger}",
        "Zum Zerreißen gespannt – am Ende reißt es für {verlierer}: {score} für {sieger}",
        "Effektivität schlägt Ästhetik: {sieger} gewinnt knapp – {score}",
        "So eng, dass es weh tut – zumindest {verlierer}: {score} für {sieger}"
    ],

    // ---- Remis mit Toren ----------------------------------------------------
    remis_torreich: [
        "Wilde Punkteteilung: {heim} und {gast} trennen sich {score}",
        "Offener Schlagabtausch endet {score} – keiner wollte verlieren",
        "{heim} und {gast} liefern sich ein packendes {score}",
        "Tore satt, aber kein Sieger: {score} zwischen {heim} und {gast}",
        "Spektakel ohne Happy End: {heim} und {gast} teilen die Punkte",
        "Zweimal Führung, zweimal Ausgleich? Am Ende steht das {score}",
        "{heim} und {gast} schenken sich nichts – gerechtes {score}",
        "Die Abwehrreihen hatten frei: {score} im Duell {heim} gegen {gast}",
        "Unterhaltung pur, Ertrag mau: {heim} und {gast} spielen {score}",
        "Beide treffen, keiner gewinnt – {score}",
        "Punkteteilung nach turbulenten 90 Minuten: {score}",
        "{heim} verpasst den Sieg, {gast} rettet einen Punkt – {score}",
        "Torreiches Remis: {heim} und {gast} neutralisieren sich beim {score}",
        "Wer offensiv spielt, wird nicht immer belohnt: {score}",
        "Ein Remis, das sich wie zwei verlorene Punkte anfühlt – für beide",
        "{heim} und {gast} verlassen den Platz mit gemischten Gefühlen ({score})",
        "Rasantes Spiel, salomonisches Ende: {score}",
        "Vier Augenpaare aufs Ergebnis, ein Achselzucken: {score}",
        "Der Fußball-Gott entschied auf Unentschieden: {score}",
        "{heim} gegen {gast} – ein {score}, das Lust auf das Rückspiel macht",
        "Treffer auf beiden Seiten, Sieger nirgends: {score}",
        "{heim} und {gast} tun sich nicht weh – jedenfalls nicht genug: {score}",
        "Am Ende steht die gerechteste aller Zahlen: {score}",
        "Führungen sind zum Ausgleichen da – {heim} und {gast} beweisen es",
        "Wer trifft, will mehr – bekommen haben beide gleich viel: {score}",
        "{heim} und {gast} schenken den Fans Tore, sich selbst nur einen Punkt",
        "Remis mit Charakter: {heim} und {gast} trennen sich {score}",
        "Das Streben nach drei Punkten endet für beide bei einem: {score}",
        "Die Null hält nicht – das Ergebnis schon: {score}",
        "Punkteteilung, Torteilung, Gefühlsteilung: {heim} gegen {gast} endet {score}",
        "Jubel hüben wie drüben – nur der Sieger fehlt: {score}",
        "Es ging hin und her – geblieben ist ein {score}",
        "Angriffslust auf beiden Seiten – Ertrag: je ein Punkt ({score})",
        "Verlieren verboten, gewinnen unmöglich: {score}",
        "Der Ausgleich als Lebensversicherung: {heim} und {gast} nehmen je einen Punkt mit",
        "Ein Unentschieden, zwei Sichtweisen: gewonnener Punkt oder verlorene zwei? {heim} und {gast} entscheiden selbst",
        "Torhüter geschlagen, Teams nicht: {score}",
        "Ergebnisgerechtigkeit oder doppelte Enttäuschung? {heim} gegen {gast}: {score}",
        "Wie man's nimmt: Für {heim} zu wenig, für {gast} zu wenig – für die Zuschauer genug",
        "Das Toreschießen klappt, das Siegen nicht: {heim} und {gast} spielen {score}",
        "Zwei Namen, ein Ergebnis, keine Antwort: {heim} gegen {gast} endet {score}",
        "Remis der Marke 'ehrlich': {score}",
        "{heim} und {gast} nehmen sich gegenseitig die Punkte weg – und schenken sich je einen",
        "Am Ende gleicht sich alles aus – buchstäblich: {score}",
        "Kein Sieger, aber auch kein Verlierer: {heim} und {gast} trennen sich versöhnlich",
        "Die Beute wird geteilt: {heim} und {gast} nehmen je einen Punkt",
        "Offensiv gedacht, remis gemacht: {score}",
        "Zwischen Freude und Frust liegt ein schmaler Grat – und ein {score}",
        "{heim} und {gast} duellieren sich auf Augenhöhe – das Ergebnis bestätigt es",
        "Ein Punkt für den einen, ein Punkt für den anderen: {heim} und {gast} vertagen die Entscheidung",
        "Getroffen, gekämpft, geteilt: {score} zwischen {heim} und {gast}",
        "So klingt Unentschieden in Zahlen: {score}"
    ],

    // ---- 0:0 ------------------------------------------------------------------
    remis_torlos: [
        "Zähes Nullnummern-Duell zwischen {heim} und {gast}",
        "Viel Kampf, keine Tore: {heim} und {gast} trennen sich 0:0",
        "Die Zuschauer hätten sich mehr gewünscht – 0:0 zwischen {heim} und {gast}",
        "Abwehrschlacht ohne Ertrag: {heim} und {gast} torlos",
        "Chancen ja, Tore nein: 0:0 im Duell {heim} gegen {gast}",
        "{heim} und {gast} belauern sich 90 Minuten – Endstand 0:0",
        "Ein Punkt, null Tore, wenig Erkenntnisse: {heim} gegen {gast}",
        "Torhüter arbeitslos? Von wegen – aber es bleibt beim 0:0",
        "Magere Kost: {heim} und {gast} verabschieden sich torlos",
        "Sicherheit zuerst: {heim} und {gast} riskieren nichts – 0:0",
        "Das Toreschießen fällt heute aus: 0:0 zwischen {heim} und {gast}",
        "{heim} beißt sich an {gast} die Zähne aus – 0:0",
        "Taktik-Schach ohne Matt: {heim} und {gast} spielen 0:0",
        "Niemand blinzelt zuerst: torloses Remis zwischen {heim} und {gast}",
        "Solide, leidenschaftlich, torlos – {heim} gegen {gast} endet 0:0",
        "Die Null steht – auf beiden Seiten: {heim} gegen {gast}",
        "90 Minuten Anlauf, kein Abschluss: 0:0",
        "{heim} und {gast} teilen die Punkte, die Torschützenliste bleibt leer",
        "Wer auf Tore hoffte, wurde enttäuscht: {heim} gegen {gast} 0:0",
        "Ein 0:0, das man schnell wieder vergisst",
        "Null Tore, viel Laufarbeit: {heim} und {gast} neutralisieren sich",
        "Die Anzeigetafel hätte frei nehmen können: {heim} gegen {gast} endet 0:0",
        "Beide Torhüter halten, was zu halten ist – mehr war da nicht: {heim} gegen {gast} 0:0",
        "Ein Abend für die Taktiktafel, nicht fürs Herz: 0:0",
        "{heim} und {gast} einigen sich stillschweigend aufs Minimalprogramm",
        "Wenig Risiko, weniger Torraumszenen, keine Tore: {heim} gegen {gast}",
        "Die Nullnummer hat viele Väter: {heim} und {gast} liefern beide Argumente",
        "0:0 – manchmal sagt ein Ergebnis alles",
        "Geduldsprobe ohne Belohnung: {heim} und {gast} torlos vereint",
        "Bloß nicht verlieren, lautete offenbar die Devise – beidseitig: 0:0",
        "Die Fans warten aufs Tor – vergeblich. {heim} gegen {gast}: 0:0",
        "Zwei Defensivreihen im Bestzustand, zwei Sturmreihen im Streik: 0:0",
        "{heim} und {gast} umkreisen sich wie Schachspieler – Remis, logisch",
        "Höhepunkte? Bitte im Rückspiel nachreichen. {heim} gegen {gast}: 0:0",
        "Vorsicht war Trumpf: {heim} und {gast} trennen sich torlos",
        "Ein Punkt fürs Bemühen, null Tore fürs Publikum: {heim} gegen {gast}",
        "Der Ball wollte einfach nicht rein – auf beiden Seiten: 0:0",
        "Zu wenig Mut, zu viel Respekt: {heim} und {gast} spielen 0:0",
        "Man kennt sich, man schätzt sich, man trifft nicht: 0:0 zwischen {heim} und {gast}",
        "Torlos glücklich? Wohl kaum. {heim} und {gast} teilen die Punkte",
        "Es fehlte an allem, was Tore bringt: {heim} gegen {gast} 0:0",
        "Die Stürmer blieben Zuschauer: torloses Remis zwischen {heim} und {gast}",
        "Ein 0:0, das niemandem weh tut – und niemanden weiterbringt",
        "Betonfußball in Reinkultur: {heim} und {gast} ohne Treffer",
        "Wer auf ein Spektakel hoffte, war im falschen Stadion: 0:0",
        "Chancenarm, torlos, punktgeteilt: {heim} gegen {gast}",
        "Auch das ist Fußball: {heim} und {gast} beharken sich zum 0:0",
        "90 Minuten Mühe, 0 Tore Lohn: {heim} und {gast}",
        "Ein Spiel für Statistiker: erste Halbzeit 0:0, zweite auch",
        "Torflaute mit Beteiligung von {heim} und {gast}",
        "Kein Durchkommen, nirgends: 0:0 zwischen {heim} und {gast}",
        "Am Ende ein Ergebnis wie ein Achselzucken: 0:0"
    ],

    // ---- Außenseiter schlägt klaren Favoriten --------------------------------
    ueberraschung: [
        "Sensation! {sieger} schockt Favorit {verlierer} mit {score}",
        "David schlägt Goliath: {sieger} stürzt {verlierer} – {score}",
        "Wer hatte DAS auf dem Zettel? {sieger} besiegt {verlierer}!",
        "Blamage für {verlierer}: Außenseiter {sieger} jubelt beim {score}",
        "{sieger} schreibt ein Fußball-Märchen – {verlierer} fassungslos",
        "Coup des Spieltags: {sieger} ringt {verlierer} mit {score} nieder",
        "Favoritensterben! {verlierer} strauchelt gegen {sieger}",
        "{sieger} über sich hinausgewachsen – {verlierer} entzaubert",
        "Das Wunder von {sieger}? {score} gegen {verlierer}!",
        "{verlierer} unterschätzt {sieger} – und zahlt die Rechnung: {score}",
        "Aufstand der Kleinen: {sieger} lässt {verlierer} alt aussehen",
        "Paukenschlag! {sieger} gewinnt tatsächlich mit {score} gegen {verlierer}",
        "{verlierer} in der Krise? {sieger} liefert den Beweis: {score}",
        "Die Sensation ist perfekt: {sieger} schlägt {verlierer}",
        "Ausgerechnet {sieger}! {verlierer} verliert {score}",
        "{sieger} kämpft, {verlierer} schläft – Überraschung beim {score}",
        "Gänsehaut bei {sieger}: der Favorit {verlierer} geht baden",
        "Keiner gab {sieger} eine Chance – {score} gegen {verlierer}!",
        "{verlierer} stolpert über mutiges {sieger}",
        "Fußball-Logik ausgehebelt: {sieger} besiegt {verlierer} mit {score}",
        "Das Papier sagt {verlierer}, der Platz sagt {sieger}: {score}",
        "Vergesst die Prognosen: {sieger} schlägt {verlierer}!",
        "Große Namen schießen keine Tore: {sieger} gewinnt {score}",
        "{verlierer} rechnet mit drei Punkten – {sieger} durchkreuzt die Rechnung",
        "Umsturz im Kleinen: {sieger} entthront {verlierer} für einen Nachmittag",
        "So schnell dreht sich der Fußball: {sieger} schockt {verlierer} mit {score}",
        "Mut schlägt Ruhm: {sieger} ringt {verlierer} nieder",
        "Riesenüberraschung! {sieger} lässt {verlierer} verzweifeln – {score}",
        "Wer ist hier der Favorit? {sieger} beantwortet die Frage neu – {score} gegen {verlierer}",
        "Achtung, Stolperfalle! {verlierer} tappt gegen {sieger} voll hinein",
        "{sieger} feiert den Coup, {verlierer} sucht Ausreden – {score}",
        "Die Hierarchie gerät ins Wanken: {sieger} besiegt {verlierer}",
        "Ein Sieg für alle, die an Wunder glauben: {sieger} schlägt {verlierer}",
        "Favoritenrolle? Zerknüllt und weggeworfen – {verlierer} verliert {score} gegen {sieger}",
        "Das passiert, wenn man {sieger} unterschätzt: {score}",
        "{verlierer} wollte nur die Pflicht erfüllen – {sieger} hatte andere Pläne",
        "Über Nacht zum Helden: {sieger} stürzt {verlierer} vom Sockel",
        "Zwergenaufstand geglückt: {sieger} triumphiert über {verlierer}",
        "Es sind Spiele wie diese, für die der Fußball erfunden wurde: {sieger} schlägt {verlierer}",
        "Der Größere fällt tiefer: {verlierer} verliert {score} gegen {sieger}",
        "Papierform? Schall und Rauch! {sieger} gewinnt {score}",
        "{sieger} schreibt die Geschichte des Spieltags – {verlierer} liefert die Pointe",
        "Ungläubige Blicke bei {verlierer}: {score} gegen {sieger}",
        "Herz schlägt Etat: {sieger} bezwingt {verlierer}",
        "Da staunt die Liga: {sieger} nimmt {verlierer} die Punkte ab",
        "Denkzettel für {verlierer}: Fußball wird auf dem Platz entschieden – {score} für {sieger}",
        "Vom Außenseiter zum Spielverderber: {sieger} düpiert {verlierer}",
        "Wenn der Underdog beißt: {score} für {sieger}",
        "{verlierer} lernt schmerzhaft: Es gibt keine kleinen Gegner – {sieger} gewinnt {score}",
        "Sensationell, verdient, unvergessen: {sieger} schlägt {verlierer}",
        "Der Favoritenschreck geht um: {sieger} erlegt {verlierer}",
        "Erst belächelt, dann gefeiert: {sieger} gewinnt gegen {verlierer}"
    ],

    // ---- Beide Teams oben in der Tabelle (Remis möglich!) --------------------
    spitzenspiel: [
        "Gipfeltreffen! {heim} und {gast} liefern sich ein Duell auf Augenhöhe – {score}",
        "Das Topspiel hält, was es verspricht: {heim} gegen {gast} endet {score}",
        "Showdown an der Spitze: {heim} empfängt {gast} – Endstand {score}",
        "Spitzenspiel unter Flutlicht-Atmosphäre: {score} zwischen {heim} und {gast}",
        "Wenn die Großen sich treffen: {heim} gegen {gast} – {score}",
        "{sieger} gewinnt das Gipfeltreffen gegen {verlierer} mit {score}",
        "Big Points! {sieger} entscheidet das Topspiel gegen {verlierer} für sich",
        "{sieger} setzt im Titelrennen ein Ausrufezeichen – {score} gegen {verlierer}",
        "Machtwechsel an der Spitze? {sieger} schlägt {verlierer} mit {score}",
        "Im Duell der Schwergewichte behält {sieger} die Oberhand",
        "{sieger} gewinnt den Kracher gegen {verlierer} – die Konkurrenz schaut genau hin",
        "Reifeprüfung bestanden: {sieger} bezwingt {verlierer} im Spitzenspiel",
        "Das Spitzenspiel zwischen {heim} und {gast} endet {score} – die Tabelle bleibt eng",
        "Kein Sieger im Gipfeltreffen: {heim} und {gast} trennen sich {score}",
        "{sieger} meldet Titelansprüche an – {score} im Topspiel gegen {verlierer}",
        "Charaktertest an der Spitze: {sieger} löst die Aufgabe gegen {verlierer}",
        "Die Liga blickt auf dieses Spiel – und {sieger} liefert ab ({score})",
        "Prestige, Punkte, Tabellenführung: {sieger} nimmt alles mit",
        "Duell der Titanen endet {score} – {heim} gegen {gast}",
        "Topspiel mit Ansage: {heim} und {gast} spielen {score}",
        "Wenn es zählt, ist {sieger} zur Stelle: Sieg im Topspiel gegen {verlierer}",
        "Ansage an die Liga: {sieger} gewinnt den Showdown gegen {verlierer}",
        "{sieger} gewinnt das Duell der Besten – {score}",
        "Wegweisender Sieg: {sieger} setzt sich im Gipfeltreffen durch",
        "Das Topspiel als Standortbestimmung: {sieger} besteht, {verlierer} wankt",
        "{sieger} gewinnt den Vergleich der Titelkandidaten – {score}",
        "Oben wird es einsamer: {sieger} distanziert {verlierer}",
        "Gipfelstürmer {sieger}: {verlierer} muss sich beim {score} geschlagen geben",
        "Wer Meister werden will, gewinnt solche Spiele: {sieger} tut es – {score}",
        "Charakter, Klasse, drei Punkte: {sieger} schlägt {verlierer} im Spitzenspiel",
        "Das Spitzenduell geht an {sieger} – {verlierer} bleibt der Frust",
        "Machtprobe bestanden: {sieger} lässt {verlierer} im Topspiel abblitzen",
        "{sieger} liefert die Antwort auf dem Rasen – {verlierer} bleibt stumm: {score}",
        "Ein Statement zur richtigen Zeit: {sieger} gewinnt das Gipfeltreffen {score}",
        "Die Liga schaut hin – und sieht {sieger} obenauf: {score} gegen {verlierer}",
        "Patt an der Spitze: {heim} und {gast} trennen sich {score}",
        "Das Gipfeltreffen bringt keine Klärung – {score} zwischen {heim} und {gast}",
        "Auf Augenhöhe, bis zum Schlusspfiff: {heim} gegen {gast} endet {score}",
        "Niemand blinzelt im Duell der Großen: {score}",
        "Das Titelrennen bleibt offen: {heim} und {gast} teilen die Punkte",
        "Viel Prestige, wenig Bewegung: {heim} gegen {gast} endet {score}",
        "Im Duell der Topteams gibt keiner nach: {score}",
        "Die Konkurrenz freut sich still: {heim} und {gast} nehmen sich gegenseitig Punkte ab",
        "Standesgemäßes Kräftemessen ohne Sieger: {score}",
        "Der große Schlagabtausch endet diplomatisch: {heim} gegen {gast} {score}",
        "Zwei Titelanwärter, ein Ergebnis, null Erkenntnis: {score}",
        "Oben bleibt alles beim Alten: {heim} und {gast} trennen sich {score}",
        "Das Topspiel hält die Spannung – vor allem für die kommenden Wochen: {score}",
        "Gipfeltreffen mit Sicherheitsabstand: {heim} und {gast} remis",
        "Wenn zwei sich nicht trauen: {score} im Spitzenspiel",
        "Ein Remis, das sich nach Warten anfühlt: {heim} gegen {gast} {score}"
    ],

    // ---- Beide Teams im Tabellenkeller (Remis möglich!) ----------------------
    kellerduell: [
        "Abstiegskrimi! {heim} und {gast} kämpfen um jeden Zentimeter – {score}",
        "Kellerduell mit Nervenflattern: {heim} gegen {gast} endet {score}",
        "Sechs-Punkte-Spiel im Tabellenkeller: {score} zwischen {heim} und {gast}",
        "Im Kampf ums Überleben trennen sich {heim} und {gast} {score}",
        "{sieger} verschafft sich Luft im Abstiegskampf – {score} gegen {verlierer}",
        "Befreiungsschlag! {sieger} gewinnt das Kellerduell gegen {verlierer}",
        "{sieger} lebt noch! Wichtiger {score}-Sieg gegen {verlierer}",
        "Für {verlierer} wird es dunkel: Niederlage im Kellerduell gegen {sieger}",
        "{sieger} klettert, {verlierer} zittert – {score} im Abstiegsduell",
        "Big Points im Keller: {sieger} schlägt {verlierer} mit {score}",
        "Dieses {score} könnte am Saisonende Gold wert sein – {sieger} jubelt",
        "Angstgegner Abstieg: {heim} und {gast} spielen {score}",
        "Wer verliert, verliert doppelt – am Ende trifft es {verlierer}",
        "Kellerduell ohne Sieger: {heim} und {gast} hilft das {score} nur bedingt",
        "Ein Punkt, der keinem so richtig hilft: {score} im Abstiegskampf",
        "{sieger} kämpft sich aus dem Tabellenkeller – {verlierer} bleibt unten drin",
        "Existenzkampf pur: {sieger} behält gegen {verlierer} die Nerven",
        "Der Druck war greifbar – {sieger} hält ihm stand ({score})",
        "Unten bleibt es eng: {heim} gegen {gast} endet {score}",
        "Abstiegsgipfel in {score}-Stimmung: {heim} und {gast} lassen Punkte liegen",
        "Drei Punkte wie ein Rettungsring: {sieger} schlägt {verlierer}",
        "Aufatmen bei {sieger}, Alarmstufe Rot bei {verlierer} – {score}",
        "Im Duell der Angeschlagenen steht {sieger} wieder auf – {score}",
        "{sieger} gewinnt das Spiel, das keiner verlieren durfte – {verlierer} tat es",
        "Der Abstiegskampf hat einen Gewinner: {sieger} siegt {score}",
        "Hoffnung tanken: {sieger} lässt {verlierer} im Tabellenkeller zurück",
        "Wer kämpft, kann gewinnen: {sieger} beweist es gegen {verlierer}",
        "{verlierer} verliert das Kellerduell gegen {sieger} – und vielleicht noch viel mehr",
        "Ein Sieg, der doppelt zählt: {sieger} bezwingt {verlierer} im Abstiegskampf",
        "Grund zum Jubeln im Tabellenkeller: {sieger} gewinnt {score}",
        "{sieger} zieht den Kopf aus der Schlinge – {verlierer} steckt fester denn je",
        "Überlebenswille schlägt Angst: {sieger} besiegt {verlierer}",
        "Im Keller gehen die Lichter an – bei {sieger}: {score}",
        "Das nackte Überleben als Antrieb: {sieger} ringt {verlierer} nieder",
        "Für {verlierer} wird die Luft dünner – {sieger} atmet durch: {score}",
        "Ein Remis wie ein Strohhalm: {heim} und {gast} klammern sich daran",
        "Angst frisst Mut: {heim} und {gast} trennen sich {score}",
        "Das Kellerduell endet, wie es geführt wurde: verkrampft – {score}",
        "Kein Befreiungsschlag, nirgends: {heim} gegen {gast} {score}",
        "Zwei Sorgenkinder, ein geteilter Punkt: {score}",
        "Der Blick auf die Tabelle bleibt für {heim} und {gast} ungemütlich: {score}",
        "Im Abstiegskampf gilt: bloß nicht verlieren. Mission erfüllt – mehr nicht: {score}",
        "{heim} und {gast} verharren im Krisenmodus – {score}",
        "Ein Pflaster auf die Wunde – mehr ist das {score} für {heim} und {gast} nicht",
        "Wer sollte hier gewinnen? Am Ende: niemand. {heim} gegen {gast} {score}",
        "Die Angst spielte mit – bei beiden: {score} im Kellerduell",
        "Rettung sieht anders aus: {heim} und {gast} teilen sich einen mageren Punkt",
        "Unten bleibt alles eng, alles bang: {heim} gegen {gast} endet {score}",
        "Das Tabellenende rückt keinen Millimeter: {score} zwischen {heim} und {gast}",
        "Remis im Keller – die Konkurrenz reibt sich die Hände: {score}",
        "Mut zum Risiko? Fehlanzeige. {heim} und {gast} begnügen sich mit {score}"
    ]
};

// ============================================================================
// PAKET 2 – Kontext-Schlagzeilen (Spiel des Tages). Anlassbezogen statt score-basiert.
// Struktur: reasonKey → { win: [...], draw: [...] }
//   win  = Sieg-Zeilen (Slots {sieger}/{verlierer}/{heim}/{gast}/{score})
//   draw = Remis-Zeilen (KEINE {sieger}/{verlierer}!; nur {heim}/{gast}/{score})
// Leeres Array → Assembler fällt automatisch auf die Score-Schlagzeile (window.REPORTS) zurück.
// reasonKeys (aus _matchInterest): derby, tradition, topduell, abstiegskrimi, europa,
//   rangduell, formstark, formkrise, ueberraschung.
// Spec: fable-deliverables/paket2-kontext/SPEC.md
// ============================================================================
window.REPORTS_CONTEXT = {
    // symmetrisch: beide Teams teilen den Anlass → {sieger}/{verlierer} dürfen ihn tragen
    derby: {
        win: [
            "Derbysieger! {sieger} entscheidet das Prestigeduell gegen {verlierer} mit {score}",
            "Im Derby zählt nur eins – und dieses eine holt sich {sieger}",
            "Stadtgespräch: {sieger} schnappt sich den Derbysieg gegen {verlierer}",
            "Das Derby gehört {sieger} – {verlierer} bleibt nur der Spott der Nachbarschaft",
            "Lokale Machtverhältnisse geklärt, zumindest bis zum nächsten Mal: {score} für {sieger}",
            "Derbyzeit ist Zuspitzung: {sieger} jubelt, {verlierer} schweigt – {score}",
            "Kurze Wege, große Gefühle: {sieger} gewinnt das Nachbarschaftsduell {score}",
            "Wochenlanges Sticheln gesichert: {sieger} gewinnt das Derby gegen {verlierer}",
            "Ein Derby vergisst man nicht – {verlierer} dieses hier leider auch nicht: {score}",
            "Die Rivalität lebt, der Jubel ist einseitig: {score} für {sieger}",
            "Derbys schreiben ihre eigenen Gesetze – heute zugunsten von {sieger} ({score})",
            "Nachbarschaftshilfe? Nicht im Derby: {sieger} schlägt {verlierer} {score}",
            "Im Duell der Rivalen behält {sieger} das letzte Wort – {score}",
            "Das ganze Umland schaut hin – und sieht {sieger} triumphieren: {score}"
        ],
        draw: [
            "Derby ohne Sieger: {heim} und {gast} trennen sich {score} – die Rivalität bleibt",
            "Ehrenrunde für niemanden: Das Nachbarschaftsduell endet {score}",
            "Geteilte Stadt, geteilte Punkte: {heim} gegen {gast} {score}",
            "Das Derby hält die Spannung – aufgeschoben aufs nächste Aufeinandertreffen: {score}",
            "Viel Feuer, kein Sieger: {heim} und {gast} liefern sich ein {score}",
            "Im Derby schenkt sich niemand etwas – auch keine Punkte: je einer für {heim} und {gast}",
            "Die Nachbarschaft bleibt unentschieden: {score} zwischen {heim} und {gast}",
            "Derbyfieber, nüchternes Ende: {heim} und {gast} teilen sich die Beute – {score}",
            "Keiner will dem anderen den Triumph gönnen: {score} im Lokalduell"
        ]
    },
    // ASYMMETRISCH: nicht festlegen, welche Seite die Tradition trägt
    tradition: {
        win: [
            "Große Namen, großes Spiel – und ein Sieger: {sieger} schlägt {verlierer} {score}",
            "Wo Tradition aufläuft, ist der Rahmen groß – gefüllt hat ihn {sieger}: {score}",
            "Ein Duell mit Geschichte, entschieden in der Gegenwart: {sieger} gewinnt {score}",
            "Vor dieser Kulisse zu bestehen, ist eine Ansage: {sieger} bezwingt {verlierer}",
            "Alte Größe schützt vor Toren nicht – auf dem Platz jubelt {sieger}: {score}",
            "Geschichte schreibt man auf dem Rasen: Dieses Kapitel gehört {sieger} ({score})",
            "Ein Spiel für die Chronik – mit {sieger} in der Hauptrolle: {score} gegen {verlierer}",
            "Namen gewinnen keine Spiele, Tore schon: {score} für {sieger}",
            "Im Duell mit Vergangenheit gewinnt die Gegenwart: {sieger} siegt {score}",
            "Das Flair eines besonderen Duells, das Ergebnis eine Sache für {sieger}: {score}",
            "Wo Aura im Spiel ist, braucht es Substanz – {sieger} hatte sie: {score}",
            "Ehrfurcht ist keine Taktik – {sieger} nimmt {verlierer} die Punkte ab: {score}",
            "Der Glanz vergangener Tage traf auf das Hier und Jetzt – {score} für {sieger}"
        ],
        draw: [
            "Ein Duell mit Geschichte, ein Ergebnis ohne Antwort: {score}",
            "Große Bühne, geteilte Punkte: {heim} und {gast} trennen sich {score}",
            "Der Chronist notiert ein {score} – und freut sich aufs Wiedersehen von {heim} und {gast}",
            "Aura trifft Alltag: {heim} gegen {gast} endet {score}",
            "Kein Sieger in einem Spiel, das mehr versprach als ein {score}",
            "Zwischen Nostalgie und Tabelle liegt ein {score}: {heim} gegen {gast}",
            "Auch besondere Duelle enden manchmal salomonisch: {score}",
            "Die Geschichte dieses Duells bekommt ein Unentschieden-Kapitel: {heim} gegen {gast} {score}"
        ]
    },
    // symmetrisch: beide oben (Spitzenspiel 1.BL / Aufstiegsduell darunter) → neutral zu beidem
    topduell: {
        win: [
            "Duell der Tabellen-Elite: {sieger} setzt sich gegen {verlierer} durch – {score}",
            "Oben angekommen, oben geblieben: {sieger} gewinnt den Vergleich der Besten",
            "Wer oben steht, will da bleiben – {sieger} tut mehr dafür: {score} gegen {verlierer}",
            "Direktes Duell, direkte Antwort: {sieger} schlägt {verlierer} im Topspiel",
            "Kein Fernduell, sondern Mann gegen Mann: {sieger} gewinnt {score}",
            "Das Duell an der Spitze geht an {sieger} – {verlierer} muss neu rechnen",
            "Big Points unter Konkurrenten: {sieger} nimmt sie {verlierer} ab – {score}",
            "In der Spitzengruppe gibt {sieger} den Ton an: {score} gegen {verlierer}",
            "Der direkte Vergleich spricht ab sofort für {sieger}: {score}",
            "Ein Sieg im direkten Duell zählt doppelt – {sieger} weiß das: {score}",
            "{sieger} besteht den Härtetest gegen {verlierer} – {score} im Duell der Topteams",
            "Ganz oben wird nichts verschenkt: {sieger} holt sich die Punkte gegen {verlierer}",
            "Rückenwind für die kommenden Wochen: {sieger} gewinnt das Topduell {score}"
        ],
        draw: [
            "Oben ändert sich nichts – genau das ist die Nachricht: {score} zwischen {heim} und {gast}",
            "Das Duell der Topteams vertagt die Entscheidung: {score}",
            "Auf Augenhöhe, wie es die Tabelle versprach: {heim} gegen {gast} {score}",
            "Beide bleiben dran – aneinander: {score} im Spitzenduell",
            "Wer gehofft hatte, dass sich oben jemand absetzt, wartet weiter: {score}",
            "Am Ende steht oben ein Gleichstand mehr: {heim} gegen {gast} {score}",
            "Die Spitzengruppe bleibt beisammen: {heim} und {gast} teilen die Punkte",
            "Zwei Ambitionierte, eine vertagte Entscheidung: {score} zwischen {heim} und {gast}"
        ]
    },
    // symmetrisch: beide im Tabellenkeller
    abstiegskrimi: {
        win: [
            "Drei Punkte gegen die Angst: {sieger} gewinnt das Kellerduell gegen {verlierer}",
            "Wer unten gewinnt, gewinnt doppelt: {sieger} nimmt {verlierer} die Hoffnung ab – {score}",
            "Existenzkampf mit klarem Ausgang: {score} für {sieger}",
            "Im Duell der Bedrängten hält {sieger} dem Druck stand – {verlierer} nicht",
            "Das Zittern hat sich gelohnt – für {sieger}: {score} im Abstiegsduell",
            "Ein Sieg, der sich wie Rettung anfühlt: {sieger} bezwingt {verlierer} – {score}",
            "Abstiegskampf ist Kopfsache – {sieger} beweist Nerven: {score}",
            "Die Nacht wird ruhiger bei {sieger}, länger bei {verlierer}: {score}",
            "Zwischen Hoffen und Bangen liegt ein Sieg: {sieger} holt ihn gegen {verlierer}",
            "Unten zählt jeder Punkt dreifach – {sieger} nimmt gleich alle mit: {score}",
            "Der Keller hat gesprochen: {sieger} bleibt dran, {verlierer} bleibt zurück – {score}",
            "Kampf, Krampf, Erlösung: {sieger} gewinnt das Duell der Sorgenkinder {score}",
            "Wer solche Spiele verliert, hat ein Problem – {verlierer} hat jetzt eins mehr ({score})"
        ],
        draw: [
            "Das Remis rettet keinen: {heim} und {gast} bleiben im Zitterbereich – {score}",
            "Im Kellerduell siegt niemand – und genau das ist das Problem: {score}",
            "Zwei Sorgen, je ein Punkt: {heim} gegen {gast} {score}",
            "Gewonnen hat nur die Ungewissheit: {score} zwischen {heim} und {gast}",
            "Unten hilft nur Siegen – gepunktet haben {heim} und {gast} trotzdem: {score}",
            "Der Abstiegskampf macht keine Pause, das Ergebnis schon: {score}",
            "Beide leben noch, beide zittern weiter: {heim} und {gast} trennen sich {score}",
            "Das Kellerduell löst nichts, verschiebt alles: {score}",
            "Wenig Trost, viel Restprogramm: {heim} und {gast} spielen {score}"
        ]
    },
    // symmetrisch – ABER doppeldeutig: 1.BL "Kampf um Europa", darunter Aufstiegsverfolger
    // → neutral formulieren ("begehrte Plätze", "Verfolger"), nie "Europapokal" behaupten
    europa: {
        win: [
            "Im Rennen um die begehrten Plätze legt {sieger} vor: {score} gegen {verlierer}",
            "Wer oben andocken will, braucht solche Siege: {sieger} liefert – {score}",
            "Das Verfolgerduell geht an {sieger} – {verlierer} verliert wertvollen Boden",
            "Ambitionen untermauert: {sieger} schlägt den direkten Rivalen {verlierer}",
            "Im Duell der Träumer wird {sieger} konkret: {score}",
            "Die schöne Aussicht gibt es nicht geschenkt – {sieger} erkämpft sie sich: {score}",
            "Wichtiger Dreier im Verfolgerfeld: {sieger} bezwingt {verlierer}",
            "Wer greift nach oben? {sieger} – zumindest an diesem Spieltag ({score})",
            "{sieger} hält Kurs auf die Spitzenplätze, {verlierer} muss abreißen lassen",
            "Das Rennen ist lang, aber solche Etappen entscheiden es: {score} für {sieger}",
            "Direktes Duell im Verfolgerpulk: {sieger} setzt sich durch – {score}",
            "Punkte mit Zusatzgewicht: {sieger} nimmt sie {verlierer} im Verfolgerduell ab"
        ],
        draw: [
            "Im Verfolgerduell tritt das Feld auf der Stelle: {score} zwischen {heim} und {gast}",
            "Keiner rückt vor, keiner fällt zurück: {heim} gegen {gast} endet {score}",
            "Das Rennen um die begehrten Plätze bleibt offen – {score}",
            "Ein Punkt hilft beiden ein bisschen und keinem richtig: {score}",
            "Verfolger unter sich, Stillstand als Ergebnis: {heim} gegen {gast} {score}",
            "Die Konkurrenz im Rückspiegel freut sich: {heim} und {gast} teilen die Punkte",
            "Wer nach oben will, darf solche Spiele nicht verlieren – immerhin: {score}",
            "Etappe ohne Ausreißer: {heim} und {gast} trennen sich {score}"
        ]
    },
    // symmetrisch: direkte Tabellennachbarn
    rangduell: {
        win: [
            "Das Duell auf Augenhöhe kippt zugunsten von {sieger}: {score}",
            "Tabellennachbarn im direkten Vergleich – {sieger} verschafft sich Luft: {score}",
            "Wenn Nachbarn streiten, gewinnt selten die Höflichkeit: {score} für {sieger}",
            "Der direkte Konkurrent, direkt geschlagen: {sieger} besiegt {verlierer}",
            "Im Nachbarschaftsstreit der Tabelle behält {sieger} die Oberhand: {score}",
            "Das Klassement sortiert sich neu – {sieger} gibt die Richtung vor ({score})",
            "Sechs-Punkte-Gefühl auch ohne Abstiegskampf: {sieger} schlägt {verlierer}",
            "Auf Tuchfühlung in der Tabelle – auf dem Platz mit klarem Ausgang: {score} für {sieger}",
            "Gleiche Tabellenregion, gleiche Ziele, ein Sieger: {sieger} ({score})",
            "{sieger} entscheidet das Duell der Punktnachbarn für sich – {verlierer} schaut nach hinten",
            "Wer im direkten Duell punktet, punktet doppelt: {score} für {sieger}",
            "Rangordnung geklärt – vorerst: {sieger} schlägt {verlierer} mit {score}"
        ],
        draw: [
            "Die Nachbarn bleiben Nachbarn: {heim} gegen {gast} endet {score}",
            "Nichts gewonnen, nichts verloren, nichts geklärt: {score}",
            "Das Duell der Punktnachbarn zementiert den Status quo: {score}",
            "Auf Augenhöhe rein, auf Augenhöhe raus: {heim} und {gast} spielen {score}",
            "Wer den direkten Konkurrenten nicht schlägt, bleibt, wo er ist: {score}",
            "Die Tabelle hält den Atem an – und atmet unverändert weiter: {score}",
            "Ein Remis wie ein Handschlag unter Nachbarn: {heim} gegen {gast} {score}",
            "Gleichstand unter Gleichgestellten: {score} zwischen {heim} und {gast}"
        ]
    },
    // ASYMMETRISCH: mind. ein Team in Topform – nie festlegen, welches
    formstark: {
        win: [
            "Ein Lauf traf auf Widerstand – gewonnen hat {sieger}: {score}",
            "Formkurven sind Momentaufnahmen, Ergebnisse sind Fakten: {score} für {sieger}",
            "Wo zuletzt viel gewonnen wurde, war die Messlatte hoch – drübergesprungen ist {sieger}",
            "Serien sind da, um geprüft zu werden – die Prüfung gewinnt {sieger}: {score}",
            "Schwung im Spiel: Am Ende nimmt ihn {sieger} mit – {score} gegen {verlierer}",
            "Viel Selbstvertrauen auf dem Platz – die Punkte sichert sich {sieger}: {score}",
            "Wer in Form ist, zeigt es; wer gewinnt, beweist es: {sieger} – {score}",
            "Momentum ist flüchtig, drei Punkte sind es nicht: {sieger} schlägt {verlierer}",
            "Der Formcheck hat einen Gewinner: {score} für {sieger}",
            "Lauf hin oder her – auf dem Rasen zählte nur dieser Nachmittag: {sieger} siegt {score}",
            "Heiße Phase, kühler Kopf: {sieger} entscheidet das Duell gegen {verlierer}",
            "Die Tagesform sprach ihr Urteil: {score} für {sieger}"
        ],
        draw: [
            "Wer auf die Fortsetzung einer Siegesserie wettete, bekommt ein {score}",
            "Schwung trifft Widerstand: {heim} und {gast} trennen sich {score}",
            "Formstärke garantiert nichts – das Remis beweist es: {score}",
            "Ein {score}, das Serien relativiert: {heim} gegen {gast}",
            "Das Momentum macht Pause: {heim} und {gast} teilen die Punkte",
            "Auch die beste Form beißt sich manchmal fest: {score}",
            "Der Lauf des einen, der Stolz des anderen – Ergebnis: {score}",
            "Angekündigt war Schwung, geliefert wurde Ausgeglichenheit: {score}"
        ]
    },
    // ASYMMETRISCH: mind. ein Team in der Krise – nie festlegen, welches
    formkrise: {
        win: [
            "Krisenstimmung lag in der Luft – gejubelt hat am Ende {sieger}: {score}",
            "Wo die Nerven blank liegen, hilft nur Nüchternheit: {sieger} gewinnt {score}",
            "Das Duell mit Krisen-Beigeschmack endet {score} – {sieger} nimmt die Punkte",
            "Zwischen Frust und Aufbruch: {sieger} entscheidet das Spiel gegen {verlierer}",
            "In schweren Wochen zählen einfache Wahrheiten: {score} für {sieger}",
            "Druck war genug im Spiel – standgehalten hat {sieger}: {score}",
            "Wo Zweifel mitspielen, entscheidet Charakter: {sieger} beweist ihn – {score}",
            "Ein Spiel, das mehr über Moral als über Taktik erzählte: {score} für {sieger}",
            "Die Sorgen spielten mit – die Punkte gehen trotzdem an {sieger}: {score}",
            "Von Verunsicherung war bei {sieger} wenig zu sehen: {score} gegen {verlierer}",
            "Schwere Zeiten, klares Ergebnis: {score} für {sieger}",
            "Wer durchhängt, braucht Haltepunkte; wer gewinnt, hat sie gefunden: {sieger} – {score}",
            "Gegen die Verunsicherung hilft nur Fußball: {sieger} spielt ihn – {score}"
        ],
        draw: [
            "Ein {score}, das keine Wende erzählt: {heim} gegen {gast}",
            "Die Zweifel bleiben im Spiel: {heim} und {gast} trennen sich {score}",
            "Wer Aufwind suchte, fand Flaute: {score}",
            "Ein Punkt als Trostpflaster – Heilung geht anders: {score}",
            "Zwischen Hoffnung und Hängepartie: {heim} gegen {gast} endet {score}",
            "Das Remis beruhigt niemanden so richtig: {score}",
            "Auch ein {score} kann schwer wiegen, wenn die Wochen lang sind",
            "Stimmungsaufhellung vertagt: {heim} und {gast} spielen {score}"
        ]
    },
    // ASYMMETRISCH: Über-/Unterperformer vs. Vorsaison – nie festlegen, welche Seite
    ueberraschung: {
        win: [
            "Wo die Saison Erwartungen sprengt, passt dieses Ergebnis ins Bild: {score} für {sieger}",
            "Prognosen altern schnell in dieser Saison – {sieger} gewinnt {score}",
            "Das Überraschungsmoment der Saison färbt auch auf dieses Duell ab: {sieger} siegt {score}",
            "Wer die Tabelle im Sommer getippt hat, tippt jetzt neu: {score} für {sieger}",
            "Diese Saison schreibt eigene Drehbücher – die heutige Szene gehört {sieger}: {score}",
            "Erwartungen sind Schall und Rauch, Punkte sind Punkte: {sieger} nimmt sie mit",
            "Von wegen vorhersehbar: {sieger} entscheidet das Duell gegen {verlierer} – {score}",
            "Die Story dieser Saison bekommt ein neues Kapitel – Autor: {sieger} ({score})",
            "Soll noch einer sagen, man wüsste vorher, wie es ausgeht: {score} für {sieger}",
            "Zwischen Höhenflug und Bauchlandung liegt manchmal nur ein Spieltag: {sieger} jubelt – {score}",
            "Das Duell mit Überraschungsfaktor hält sein Versprechen: {sieger} schlägt {verlierer}",
            "Wer hier auf die Vorsaison wettete, hat verloren – {sieger} gewinnt {score}"
        ],
        draw: [
            "Ausgerechnet das Duell mit Überraschungsfaktor endet gewöhnlich: {score}",
            "Diesmal keine Pointe – {heim} und {gast} trennen sich {score}",
            "Die Saison der Überraschungen gönnt sich eine Verschnaufpause: {score}",
            "Erwartung hin, Realität her – heute einigt man sich auf {score}",
            "Auch Überraschungsgeschichten haben Ruhekapitel: {heim} gegen {gast} {score}",
            "Keine neue Wendung, nur ein Punkt für jeden: {score}"
        ]
    }
};

// ============================================================================
// PAKET 3 – Vorschau-Anrisse (Spiel des Tages, VOR dem Spiel).
// Struktur: reasonKey → [ ...zeilen... ]. Slots NUR {heim}/{gast} (kein Ergebnis!).
// Leeres Array → Fallback aufs Label "Spiel des Tages · {reason}".
// Spec: fable-deliverables/paket3-vorschau/SPEC.md
// ============================================================================
window.REPORTS_PREVIEW = {
    derby: [
        "Derby-Zeit! {heim} empfängt den Rivalen {gast} – die Region hält den Atem an",
        "Kurze Anfahrt, große Rivalität: {gast} gastiert bei {heim}",
        "Wenn {heim} und {gast} aufeinandertreffen, ist Tabelle Nebensache",
        "Das Nachbarschaftsduell steigt: {heim} gegen {gast} – Zündstoff garantiert",
        "Prestige schlägt Punkte? Im Derby zwischen {heim} und {gast} gibt es beides zu holen",
        "Die Stadt spricht nur über ein Spiel: {heim} gegen {gast}",
        "Alte Rivalen, neue Rechnung: {gast} kommt zu {heim}",
        "Lokalkolorit pur: {heim} und {gast} unter sich",
        "Derbystimmung liegt in der Luft – {heim} bittet {gast} zum Tanz",
        "Nachbarn unter sich, Freunde erst nach Abpfiff: {heim} gegen {gast}",
        "Hier geht es um mehr als drei Punkte: {heim} empfängt {gast} zum Derby"
    ],
    tradition: [
        "Ein Duell mit Klang: {heim} empfängt {gast}",
        "Große Bühne im Spielplan: {heim} gegen {gast} verspricht Fußball mit Geschichte",
        "Wenn dieses Duell ruft, schauen auch Neutrale hin: {heim} – {gast}",
        "Tradition liegt in der Luft, Punkte auf dem Tisch: {heim} gegen {gast}",
        "Ein Spiel für Liebhaber: {gast} zu Gast bei {heim}",
        "Namen, die man kennt, Duelle, die man sehen will: {heim} gegen {gast}",
        "Der Spielplan schenkt uns ein besonderes Aufeinandertreffen: {heim} – {gast}",
        "Geschichte garantiert keine Punkte – Spannung garantiert dieses Duell: {heim} gegen {gast}",
        "Fußball-Romantiker, aufgepasst: {heim} empfängt {gast}",
        "Aura trifft Alltag, {heim} trifft {gast}"
    ],
    topduell: [
        "Gipfeltreffen! {heim} und {gast} kreuzen ganz oben die Klingen",
        "Das Beste, was der Spieltag zu bieten hat: {heim} gegen {gast}",
        "Oben trifft oben: {heim} empfängt {gast} zum Duell der Spitzenteams",
        "Wer bleibt vorn? {heim} und {gast} klären es unter sich",
        "Spitzenspiel mit Sprengkraft: {gast} reist zu {heim}",
        "Direkter geht es nicht: {heim} gegen {gast} im Duell der Verfolgten und Verfolger",
        "Die Konkurrenz schaut genau hin: {heim} fordert {gast} – oder umgekehrt?",
        "Wenn die Tabelle Regie führt, ist das hier der Hauptfilm: {heim} gegen {gast}",
        "Ganz oben wird abgerechnet: {heim} empfängt {gast}",
        "Zwei Ambitionen, ein Platz an der Sonne: {heim} gegen {gast}"
    ],
    abstiegskrimi: [
        "Kellerduell mit Sprengkraft: {heim} empfängt {gast} zum Spiel der Spiele im Abstiegskampf",
        "Unten zählt jedes Spiel doppelt – dieses dreifach: {heim} gegen {gast}",
        "Zwei Sorgenkinder, ein direktes Duell: {heim} gegen {gast}",
        "Wer verliert, steckt tiefer drin: {heim} empfängt {gast} im Kellerduell",
        "Sechs-Punkte-Spiel im Tabellenkeller: {gast} muss zu {heim}",
        "Im Abstiegskampf gibt es keine kleinen Spiele – aber große: {heim} gegen {gast}",
        "Zittern verboten, Punkten Pflicht: {heim} und {gast} unter Druck",
        "Das Duell, das keiner verlieren darf: {heim} gegen {gast}",
        "Existenzfragen werden auf dem Rasen beantwortet: {heim} empfängt {gast}",
        "Der Keller bebt: {heim} und {gast} spielen um mehr als drei Punkte"
    ],
    europa: [
        "Verfolgerduell mit Fernwirkung: {heim} empfängt {gast}",
        "Beide wollen nach oben – nur einer kann vorlegen: {heim} gegen {gast}",
        "Im Rennen um die begehrten Plätze kommt es zum direkten Vergleich: {heim} – {gast}",
        "Wer bleibt im Windschatten der Spitze? {heim} und {gast} klären es direkt",
        "Rückenwind zu vergeben: {heim} gegen {gast} im Duell der Verfolger",
        "Die Aussicht ist schön da oben – {heim} und {gast} wollen beide hin",
        "Ein Sieg hier zählt doppelt im Aufholrennen: {heim} empfängt {gast}",
        "Das Verfolgerfeld sortiert sich: {gast} gastiert bei {heim}",
        "Ambitionen im Direktvergleich: {heim} gegen {gast}",
        "Wer träumt weiter, wer wacht auf? {heim} gegen {gast} im Verfolgerduell"
    ],
    rangduell: [
        "Tabellennachbarn unter sich: {heim} empfängt {gast}",
        "Auf Tuchfühlung im Klassement – jetzt auf Tuchfühlung auf dem Rasen: {heim} gegen {gast}",
        "Direkter Vergleich, direkte Folgen: {heim} gegen {gast}",
        "Wer schaut nach dem Wochenende auf wen herab? {heim} und {gast} klären es",
        "Zwischen diesen beiden passt kein Blatt Papier – sagt die Tabelle: {heim} gegen {gast}",
        "Nachbarschaftsstreit der Tabelle: {gast} reist zu {heim}",
        "Gleiche Ziele, gleiche Tabellenregion: {heim} empfängt {gast}",
        "Hier geht es um die Blickrichtung: nach oben oder nach unten – {heim} gegen {gast}",
        "Das Duell der Punktnachbarn verspricht Brisanz: {heim} – {gast}",
        "Wer die Nase vorn haben will, muss hier liefern: {heim} gegen {gast}"
    ],
    formstark: [
        "Formcheck: In diesem Duell steckt zuletzt viel Schwung – {heim} empfängt {gast}",
        "Ein Lauf steht auf dem Prüfstand: {heim} gegen {gast}",
        "Wer bremst hier wen? {heim} gegen {gast} – zuletzt rollte es ordentlich",
        "Serien lieben Herausforderungen: {heim} gegen {gast} liefert eine",
        "Da kommt Schwung ins Spiel: {gast} gastiert bei {heim}",
        "Selbstvertrauen trifft Gelegenheit: {heim} empfängt {gast}",
        "Die Formkurve zeigt hier zuletzt steil nach oben – Fortsetzung offen: {heim} gegen {gast}",
        "Heiße Wochen, heißes Duell: {heim} gegen {gast}",
        "Momentum ist die härteste Währung – hier wird sie gehandelt: {heim} – {gast}",
        "Läuft es weiter? {heim} und {gast} geben die Antwort auf dem Platz"
    ],
    formkrise: [
        "Hier will jemand raus aus dem Tief – Gelegenheit dazu: {heim} gegen {gast}",
        "Krisenbewältigung auf Rasen: {heim} empfängt {gast}",
        "Die Sorgenfalten spielen mit: {heim} gegen {gast}",
        "Zuletzt lief wenig zusammen – jetzt zählt nur dieses Spiel: {heim} gegen {gast}",
        "Ein Spiel als Chance zur Wende: {heim} empfängt {gast}",
        "Der Druck sitzt mit auf der Bank: {heim} gegen {gast}",
        "Durchatmen oder weiter grübeln? Dieses Duell entscheidet mit: {heim} – {gast}",
        "Irgendwo zwischen Pflicht und Panik: {heim} gegen {gast}",
        "Ein Sieg heilt viele Wunden – das wissen hier alle: {heim} gegen {gast}",
        "Formtief trifft Fußballnachmittag: {heim} empfängt {gast} – Besserung nicht ausgeschlossen"
    ],
    ueberraschung: [
        "Die Saison hat hier schon einige Erwartungen über den Haufen geworfen: {heim} gegen {gast}",
        "Vorsaison? Vergessen Sie die Vorsaison: {heim} empfängt {gast}",
        "Hier spielt eine der Geschichten der Saison mit: {heim} gegen {gast}",
        "Tippzettel zerknüllen, hinsetzen, staunen: {heim} – {gast}",
        "Erwartung und Wirklichkeit treffen sich zum Direktvergleich: {heim} gegen {gast}",
        "Wer hätte das im Sommer gedacht? {heim} gegen {gast} hat Überraschungspotenzial",
        "Die Tabelle erzählt hier eine unerwartete Geschichte – nächstes Kapitel: {heim} gegen {gast}",
        "Höhenflüge, Bauchlandungen – diese Saison kann beides. Jetzt: {heim} gegen {gast}",
        "Formkurven, die niemand kommen sah: {heim} und {gast} im direkten Duell",
        "Das Drehbuch dieser Saison liebt Wendungen – hier könnte die nächste warten: {heim} gegen {gast}"
    ]
};
