// Namen und Schrift der Liga-Navigation und der Seitenleiste (drei Namen je Liga: voll = offiziell, mittel, kurz).
// GESCHRIEBEN VOM STIL-MODUS (··· → 🎨 Stil-Modus → Speichern) – nicht von Hand ändern. Aufbau:
//   mittel / kurz   {Liga-ID: Name}; fehlt ein Eintrag, gilt die automatische Form (Ligatyp + Region)
//   bloecke         {"p:<Liga darüber>": {handy: {schrift, punkte, pfeile}, desktop: {schrift}}} – je Geschwisterblock
//   seitenleiste    {handy: px, desktop: px} – eine einheitliche Schrift für die ganze Seitenleiste
const NAV_STIL = {
 "version": 1,
 "mittel": {},
 "kurz": {
  "1": "1. BL",
  "2": "2. BL",
  "5-1": "OL RLP/Saar",
  "5-2": "OL Bad.-Württ.",
  "5-4": "OL S.-H.",
  "5-5": "OL HH",
  "5-6": "OL NS",
  "5-7": "Bremen",
  "5-10": "OL Westfalen",
  "5-11": "OL Niederrhein",
  "6-1": "VL Südwest",
  "6-4": "VL Baden",
  "6-5": "VL Südbaden",
  "6-6": "VL Württ.",
  "6-7": "VL Hessen Nord",
  "6-8": "VL Hessen Mitte",
  "6-9": "VL Hessen Süd",
  "6-10": "LL Schleswig",
  "6-11": "LL Holstein",
  "6-12": "LL HH Hammonia",
  "6-13": "LL HH Hansa",
  "6-17": "Braunschw.",
  "6-18": "LL Bremen",
  "6-19": "VL Meckl.-Vpom.",
  "6-22": "VL Sachsen-Anh.",
  "6-25": "Westfalen St. 1",
  "6-26": "Westfalen St. 2",
  "6-27": "LL Niederrhein Gr. 1",
  "6-28": "LL Niederrhein Gr. 2",
  "6-29": "LL Mittelrhein St. 1",
  "6-30": "LL Mittelrhein St. 2",
  "6-31": "LL Bayern NW",
  "6-32": "LL Bayern NO",
  "6-33": "LL Bayern M",
  "6-34": "LL Bayern SW",
  "6-35": "LL Bayern SO",
  "7-1": "LL Südwest Ost",
  "7-2": "LL Südwest West",
  "7-3": "BZL Rhld. West",
  "7-4": "BZL Rhld. Mitte",
  "7-5": "BZL Rhld. Ost",
  "7-6": "VL Saarland Nord-Ost",
  "7-7": "VL Saarland Süd-West",
  "7-8": "LL Berlin St. 1",
  "7-9": "LL Berlin St. 2",
  "8-1": "BZL Rheinhessen",
  "8-2": "BZL Vorderpfalz",
  "8-3": "BZL Nahe",
  "8-4": "BZL Westpfalz",
  "h3-niedersachsen-amateuroberliga": "AOL NS",
  "h3-schleswigholstein-amateurliga": "AL SH",
  "h3-schleswigholstein-landesliga": "LL SH",
  "h3-schwarzwaldbodensee-amateurliga": "AL SW-Bodensee",
  "h3-badenwuerttemberg-oberliga": "OL Ba.-Wü.",
  "h3-westsuedwest-regionalliga": "RL West/SW",
  "h4-badenwuerttemberg-oberliga": "OL Ba.-Wü.",
  "h3d-neubrandenburg-bezirksliga": "BZL Neubra.",
  "h3d-frankfurtoder-bezirksliga": "BZL Frankfurt",
  "h3d-cottbus-bezirksliga": "Cottbus",
  "h3d-magdeburg-bezirksliga": "BZL Magdbg.",
  "h3d-dresden-bezirksliga": "Dresden",
  "h3d-karlmarxstadt-bezirksliga": "BZL Karl-Marx",
  "h3d-berlin-bezirksliga": "Berlin"
 },
 "bloecke": {},
 "seitenleiste": {}
};
